/**
 * @author Tinkoprof
 * @summary Creates Prism Launcher-compatible instance packages (ZIP) with necessary configurations and libraries.
 */
package sledgemc.dev.launcher;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;

import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

public class PrismPackager {

    private static final Gson GSON = new GsonBuilder().setPrettyPrinting().create();
    private final String mcVersion;

    public PrismPackager(String mcVersion) {
        this.mcVersion = mcVersion;
    }

    public void createPackage(Path destinationZip) throws IOException {
        try (ZipOutputStream zos = new ZipOutputStream(new FileOutputStream(destinationZip.toFile()))) {

            String packJson = generateMmcPack();
            zos.putNextEntry(new ZipEntry("mmc-pack.json"));
            zos.write(packJson.getBytes());
            zos.closeEntry();

            String instanceCfg = "InstanceType=OneSix\n" +
                    "name=SledgeMC-" + mcVersion + "\n" +
                    "notes=Generated by SledgeLauncher\n";
            zos.putNextEntry(new ZipEntry("instance.cfg"));
            zos.write(instanceCfg.getBytes());
            zos.closeEntry();

            String patchJson = generatePatchJson();
            zos.putNextEntry(new ZipEntry("patches/sledgemc.dev.loader.json"));
            zos.write(patchJson.getBytes());
            zos.closeEntry();

            try {
                Path sourceLoader = AssetDownloader.ensureLoader(mcVersion, System.out::println);
                zos.putNextEntry(new ZipEntry("libraries/SledgeMC-Loader-" + mcVersion + ".jar"));
                Files.copy(sourceLoader, zos);
                zos.closeEntry();
            } catch (Exception e) {
                System.err.println("[SledgeMC] Failed to include loader: " + e.getMessage());
                throw new IOException("Failed to download loader for package.", e);
            }

            try {
                Path sourceAgent = AssetDownloader.ensureAgent(System.out::println);
                zos.putNextEntry(new ZipEntry("libraries/sledge-agent.jar"));
                Files.copy(sourceAgent, zos);
                zos.closeEntry();
            } catch (Exception e) {
                System.err.println("[SledgeMC] Failed to include agent: " + e.getMessage());
            }

            try {
                Path sourceApi = AssetDownloader.ensureApi(System.out::println);
                zos.putNextEntry(new ZipEntry("libraries/sledge-api.jar"));
                Files.copy(sourceApi, zos);
                zos.closeEntry();
            } catch (Exception e) {
                System.err.println("[SledgeMC] Failed to include API: " + e.getMessage());
            }
        }
    }

    private String generateMmcPack() {
        JsonObject root = new JsonObject();
        JsonArray components = new JsonArray();

        JsonObject mc = new JsonObject();
        mc.addProperty("cachedName", "Minecraft");
        mc.addProperty("cachedVersion", mcVersion);
        mc.addProperty("important", true);
        mc.addProperty("uid", "net.minecraft");
        mc.addProperty("version", mcVersion);
        components.add(mc);

        JsonObject sledge = new JsonObject();
        sledge.addProperty("cachedName", "SledgeMC");
        sledge.addProperty("cachedVersion", "1.0.0");
        sledge.addProperty("important", true);
        sledge.addProperty("uid", "sledgemc.dev.loader");
        sledge.addProperty("version", "1.0.0");
        components.add(sledge);

        root.add("components", components);
        root.addProperty("formatVersion", 1);
        return GSON.toJson(root);
    }

    private String generatePatchJson() {
        JsonObject root = new JsonObject();
        root.addProperty("formatVersion", 1);
        root.addProperty("uid", "sledgemc.dev.loader");
        root.addProperty("name", "SledgeMC");
        root.addProperty("version", "1.0.0");
        root.addProperty("mainClass", "sledgemc.dev.loader.SledgeBootstrap");

        JsonArray libraries = new JsonArray();

        JsonObject loaderLib = new JsonObject();
        loaderLib.addProperty("name", "com.github.Astera-Solutions:SledgeMC-Loader:" + mcVersion);
        loaderLib.addProperty("MMC-hint", "local");
        loaderLib.addProperty("MMC-filename", "SledgeMC-Loader-" + mcVersion + ".jar");
        libraries.add(loaderLib);

        JsonObject agentLib = new JsonObject();
        agentLib.addProperty("name", "com.github.Astera-Solutions:SledgeMC-Agent:agent-v1.0.0");
        agentLib.addProperty("MMC-hint", "local");
        agentLib.addProperty("MMC-filename", "sledge-agent.jar");
        libraries.add(agentLib);

        JsonObject apiLib = new JsonObject();
        apiLib.addProperty("name", "com.github.Astera-Solutions:Sledge-API:v1.0.0");
        apiLib.addProperty("MMC-hint", "local");
        apiLib.addProperty("MMC-filename", "sledge-api.jar");
        libraries.add(apiLib);

        root.add("libraries", libraries);

        JsonArray jvmArgs = new JsonArray();
        jvmArgs.add("-javaagent:libraries/sledge-agent.jar");
        root.add("jvmArgs", jvmArgs);

        return GSON.toJson(root);
    }

}
